# Generated by Django 4.1.6 on 2023-02-10 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, max_length=40, null=True, verbose_name='Mobile')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Address')),
                ('ogrn_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='ОГРН')),
                ('inn_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='ИНН')),
                ('kpp_number', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('logo', models.ImageField(upload_to='images/companies/logos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company profiles',
                'ordering': ['name'],
            },
        ),
    ]
