# Generated by Django 4.1.6 on 2023-02-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aogservice',
            name='service_number',
            field=models.CharField(default='9270D0F', editable=False, max_length=7, unique=True),
        ),
    ]
