# Generated by Django 4.1.6 on 2023-02-10 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='Store location name ')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_wrhs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item')),
                ('item_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item weight')),
                ('item_serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial number')),
                ('item_part_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Part number')),
                ('item_lenght', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item lenght')),
                ('item_width', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item width')),
                ('item_height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item height')),
                ('image_document', models.FileField(blank=True, null=True, upload_to='')),
                ('is_serviceable', models.BooleanField(default=True, verbose_name='Is Serviceable?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stuffs/instr')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_instrument', to=settings.AUTH_USER_MODEL)),
                ('location_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stuffs.storelocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DutyPerson',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('position', models.CharField(max_length=50, verbose_name='Person position')),
                ('contact_phone', models.CharField(max_length=12, verbose_name='Contact Phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users persons stuff')),
            ],
            options={
                'verbose_name': 'Responsble person',
                'verbose_name_plural': 'Responsibles',
            },
        ),
        migrations.CreateModel(
            name='Aog',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item')),
                ('item_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item weight')),
                ('item_lenght', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item lenght')),
                ('item_width', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item width')),
                ('item_height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item height')),
                ('image_document', models.FileField(blank=True, null=True, upload_to='')),
                ('is_serviceable', models.BooleanField(default=True, verbose_name='Is Serviceable?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stuffs/aogs')),
                ('item_part_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Part number')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_aog', to=settings.AUTH_USER_MODEL)),
                ('location_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stuffs.storelocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcStand',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item')),
                ('item_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item weight')),
                ('item_serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial number')),
                ('item_part_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Part number')),
                ('item_lenght', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item lenght')),
                ('item_width', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item width')),
                ('item_height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item height')),
                ('image_document', models.FileField(blank=True, null=True, upload_to='')),
                ('is_serviceable', models.BooleanField(default=True, verbose_name='Is Serviceable?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stuffs/stands')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_stand', to=settings.AUTH_USER_MODEL)),
                ('location_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stuffs.storelocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcEngine',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item')),
                ('item_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item weight')),
                ('item_serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial number')),
                ('item_part_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Part number')),
                ('item_lenght', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item lenght')),
                ('item_width', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item width')),
                ('item_height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item height')),
                ('image_document', models.FileField(blank=True, null=True, upload_to='')),
                ('is_serviceable', models.BooleanField(default=True, verbose_name='Is Serviceable?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stuffs/engins')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_engine', to=settings.AUTH_USER_MODEL)),
                ('location_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stuffs.storelocation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
